[IMPROVEMENT] Deprecated the --with-gui flag for linux/configure and mac/configure
CCExtractor/ccextractor pull request #1415
Opened 2022-02-14 07:52 UTC by devmrfitz

**In raising this pull request, I confirm the following (please check boxes):**

- [X] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that another pull request for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.
- [X] **I have mentioned this change in the [changelog](https://github.com/CCExtractor/ccextractor/blob/master/docs/CHANGES.TXT).**

**My familiarity with the project is as follows (check one):**

- [ ] I have never used CCExtractor.
- [X] I have used CCExtractor just a couple of times.
- [ ] I absolutely love CCExtractor, but have not contributed previously.
- [ ] I am an active contributor to CCExtractor.

---

Since CCExtractor now has a new GUI hosted at [https://github.com/CCExtractor/ccextractorfluttergui](https://github.com/CCExtractor/ccextractorfluttergui), I have deprecated the `--with-gui` flag in mac/configure and linux/configure and indicated the same in `docs/COMPILATION.md`, as discussed on Slack.

2022-02-14 14:13 UTC, devmrfitz commented
Tests found a bug. Have fixed it

2022-02-16 20:32 UTC, canihavesomecoffee requested changes
Almost fine for me.

@cfsmp3 any remarks?

2022-02-16 20:32 UTC, canihavesomecoffee commented on docs/CHANGES.TXT
> +- Deprecated the --with-gui flag for linux/configure and mac/configure
```suggestion
- Removed the --with-gui flag for linux/configure and mac/configure (use the Flutter GUI instead)
```

2022-03-07 12:20 UTC, canihavesomecoffee approved these changes

2022-03-07 12:20 UTC, merged