[FIX] ccx_encoders_smptett.c: Enforce int for sprintf
CCExtractor/ccextractor pull request #1506
Opened 2023-03-20 11:15 UTC by marcybelardo

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.
- [x] **I have mentioned this change in the [changelog](https://github.com/CCExtractor/ccextractor/blob/master/docs/CHANGES.TXT).**

**My familiarity with the project is as follows (check one):**

- [ ] I have never used CCExtractor.
- [x] I have used CCExtractor just a couple of times.
- [ ] I absolutely love CCExtractor, but have not contributed previously.
- [ ] I am an active contributor to CCExtractor.

---

For issue #1483, refactors formatting of `col1` and `row1` variables to avoid issues with LC_NUMERIC auto-formatting float values.

2023-03-20 15:16 UTC, cfsmp3 commented on src/lib_ccx/ccx_encoders_smptett.c
> +			col1_int = col1;
This is going to trigger a compiler warning about loss of precision. i.e. use casting.

2023-03-20 16:06 UTC, marcybelardo commented on src/lib_ccx/ccx_encoders_smptett.c
> +
I've looked through a bunch of XML data and I've never seen tts:origin being used with decimal values. I'll write an implementation using whole percentage numbers now, give me a few minutes.

2023-03-20 22:48 UTC, cfsmp3 requested changes
We really don't need to use a math function to convert from a float to an int :-) (losing the fractional part). A cast will do.

I'm not sure we are OK with that unneeded lost of precision though. I'd very much prefer to keep 2 or 3 decimal places.

2023-03-21 00:18 UTC, marcybelardo commented
> We really don't need to use a math function to convert from a float to an int :-) (losing the fractional part). A cast will do.
> 
> I'm not sure we are OK with that unneeded lost of precision though. I'd very much prefer to keep 2 or 3 decimal places.

Ah 😅 well, in that case, I'll aim for two!

2023-03-21 01:26 UTC, cfsmp3 commented
Please make sure you test a bit before sending or updating a PR. Your code won't work for example for 

3.099
which will get converted to 3.99

Reopen the PR (or start a new one) only after you have tested with many values. Thanks!

2023-03-21 01:26 UTC, closed without merging

2023-03-21 02:01 UTC, marcybelardo commented
> Please make sure you test a bit before sending or updating a PR. Your code won't work for example for 
> 
> 
> 
> 3.099
> 
> which will get converted to 3.99
> 
> 
> 
> Reopen the PR (or start a new one) only after you have tested with many values. Thanks!
> 
> 

Got it, I'll work on this more~