[rust] add options module
CCExtractor/ccextractor pull request #1632
Opened 2024-08-09 22:39 UTC by prateekmedia

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [contributors guide](https://github.com/CCExtractor/ccextractor/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.
- [ ] **I have mentioned this change in the [changelog](https://github.com/CCExtractor/ccextractor/blob/master/docs/CHANGES.TXT).**

**My familiarity with the project is as follows (check one):**

- [ ] I have never used CCExtractor.
- [ ] I have used CCExtractor just a couple of times.
- [ ] I absolutely love CCExtractor, but have not contributed previously.
- [x] I am an active contributor to CCExtractor.

---

Add CCX Options in Rust module, successor to #1559

2024-08-10 11:10 UTC, PunitLodha requested changes

2024-08-10 11:10 UTC, PunitLodha commented on src/rust/lib_ccxr/src/common/constants.rs
>      /* Buffer where cc data contain 3 byte cc_valid ccdata 1 ccdata 2 */
Same comment is present twice

2024-08-10 11:10 UTC, PunitLodha commented on src/rust/lib_ccxr/src/util/encoding.rs
Encoding is merged now in #1628 , so its not needed in this PR

2024-08-10 11:25 UTC, IshanGrover2004 commented on src/rust/lib_ccxr/src/util/encoding.rs
Even all other dependent PRs are now merged @prateekmedia

2024-08-10 13:46 UTC, prateekmedia commented on src/rust/lib_ccxr/src/util/encoding.rs
@IshanGrover2004 Does that mean any change in this PR?

2024-08-10 13:50 UTC, prateekmedia commented on src/rust/lib_ccxr/src/common/constants.rs
>      /* Buffer where cc data contain 3 byte cc_valid ccdata 1 ccdata 2 */
Fixed!

2024-08-10 15:01 UTC, IshanGrover2004 commented on src/rust/lib_ccxr/src/util/encoding.rs
No its fine, Just rebase the main branch of CCExtractor as well, bcs it will have some module or code changes to the elberronnie old PR

2024-08-19 11:59 UTC, PunitLodha approved these changes

2024-08-19 11:59 UTC, PunitLodha commented on src/rust/src/common.rs
> +//                     .unwrap_or_default()
Should this be removed?

2024-08-19 15:51 UTC, prateekmedia commented on src/rust/src/common.rs
> +//                     .unwrap_or_default()
Yes, Done!

2024-08-19 16:34 UTC, merged